import type { MediaItem, Episode, WatchHistoryItem } from '@openplex/shared';

export const MOCK_FEATURED_HERO: MediaItem[] = [
  {
    id: 'hero-1',
    title: 'Squid Game: The Challenge Season 2',
    originalTitle: '오징어 게임: 더 챌린지',
    overview: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits with deadly high stakes in this dark psychological survival drama.',
    posterPath: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=1200&auto=format&fit=crop&q=80',
    backdropPath: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=1600&auto=format&fit=crop&q=80',
    mediaType: 'tv',
    voteAverage: 9.2,
    releaseDate: '2024',
    numberOfSeasons: 2,
  },
  {
    id: 'hero-2',
    title: 'Cyberpunk Neo: Shinjuku 2099',
    originalTitle: '사이버펑크 네오 신주쿠',
    overview: 'In a neon-drenched metropolis ruled by hyper-corps and augmented mercenaries, a rogue hacker uncovers an encrypted conspiracy deep inside the global quantum network.',
    posterPath: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop&q=80',
    backdropPath: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1600&auto=format&fit=crop&q=80',
    mediaType: 'anime',
    voteAverage: 8.9,
    releaseDate: '2024',
    numberOfSeasons: 1,
  },
  {
    id: 'hero-3',
    title: 'The Outlaws 4: Punishment',
    originalTitle: '범죄도시 4',
    overview: 'Monster Detective Ma Seok-do joins the Cyber Investigation Team to take down a high-profile online illegal gambling ring led by a ruthless former special forces operative.',
    posterPath: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1200&auto=format&fit=crop&q=80',
    backdropPath: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1600&auto=format&fit=crop&q=80',
    mediaType: 'movie',
    voteAverage: 8.7,
    releaseDate: '2024',
  },
];

export const MOCK_CONTINUE_WATCHING: WatchHistoryItem[] = [
  {
    id: 'hist-1',
    mediaId: 'cw-1',
    seasonNumber: 1,
    episodeNumber: 4,
    episodeTitle: 'Episode 4: The Red Door',
    progressSeconds: 1620,
    durationSeconds: 3600,
    lastWatchedAt: new Date(Date.now() - 3600 * 1000 * 3).toISOString(),
    completed: false,
    mediaItem: {
      id: 'cw-1',
      title: 'Queen of Tears',
      originalTitle: '눈물의 여왕',
      overview: 'The queen of department stores and the prince of supermarkets weather a marital crisis until love miraculously begins to bloom again.',
      posterPath: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600&auto=format&fit=crop&q=80',
      mediaType: 'tv',
      voteAverage: 9.3,
      releaseDate: '2024',
    },
  },
  {
    id: 'hist-2',
    mediaId: 'cw-2',
    seasonNumber: 1,
    episodeNumber: 12,
    episodeTitle: 'Episode 12: End of the Horizon',
    progressSeconds: 2800,
    durationSeconds: 3200,
    lastWatchedAt: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
    completed: false,
    mediaItem: {
      id: 'cw-2',
      title: 'Solo Leveling',
      originalTitle: '나 혼자만 레벨업',
      overview: 'In a world where hunters must battle deadly monsters, weak hunter Sung Jinwoo is chosen by a mysterious program, granting him the unique ability to level up infinitely.',
      posterPath: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
      mediaType: 'anime',
      voteAverage: 9.0,
      releaseDate: '2024',
    },
  },
  {
    id: 'hist-3',
    mediaId: 'cw-3',
    progressSeconds: 4500,
    durationSeconds: 7200,
    lastWatchedAt: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
    completed: false,
    mediaItem: {
      id: 'cw-3',
      title: 'Dune: Part Two',
      originalTitle: '듄: 파트 2',
      overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
      posterPath: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
      mediaType: 'movie',
      voteAverage: 8.8,
      releaseDate: '2024',
    },
  },
];

export const MOCK_TRENDING_DRAMA: MediaItem[] = [
  {
    id: 'drama-1',
    title: 'Lovely Runner',
    originalTitle: '선재 업고 튀어',
    overview: 'A devoted fan travels 15 years back in time to change the tragic fate of her ultimate idol and save his life.',
    posterPath: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    mediaType: 'tv',
    voteAverage: 9.1,
    releaseDate: '2024',
  },
  {
    id: 'drama-2',
    title: 'Moving',
    originalTitle: '무빙',
    overview: 'Children with superpowers and their parents who harbor painful secrets from the past face enormous impending perils together.',
    posterPath: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    mediaType: 'tv',
    voteAverage: 9.4,
    releaseDate: '2023',
  },
  {
    id: 'drama-3',
    title: 'A Killer Paradox',
    originalTitle: '살인자ㅇ난감',
    overview: 'When one accidental murder leads to another, an ordinary college student finds himself trapped in an endless cat-and-mouse chase with a shrewd detective.',
    posterPath: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    mediaType: 'tv',
    voteAverage: 8.5,
    releaseDate: '2024',
  },
  {
    id: 'drama-4',
    title: 'Death\'s Game',
    originalTitle: '이재, 곧 죽습니다',
    overview: 'Facing continuous setbacks, a desperate man takes his own life only to be punished by Death with living through 12 imminent reincarnations.',
    posterPath: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&auto=format&fit=crop&q=80',
    mediaType: 'tv',
    voteAverage: 8.9,
    releaseDate: '2024',
  },
  {
    id: 'drama-5',
    title: 'The Glory',
    originalTitle: '더 글로리',
    overview: 'Years after surviving horrific school abuse, a former victim puts an elaborate revenge scheme into motion to make the perpetrators pay for their crimes.',
    posterPath: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=600&auto=format&fit=crop&q=80',
    mediaType: 'tv',
    voteAverage: 9.0,
    releaseDate: '2023',
  },
];

export const MOCK_POPULAR_MOVIES: MediaItem[] = [
  {
    id: 'mov-1',
    title: 'Exhuma',
    originalTitle: '파묘',
    overview: 'The process of excavating an ominous grave unleashes dreadful consequences buried underneath for a family plagued by mysterious occurrences.',
    posterPath: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=600&auto=format&fit=crop&q=80',
    mediaType: 'movie',
    voteAverage: 8.8,
    releaseDate: '2024',
  },
  {
    id: 'mov-2',
    title: 'Oppenheimer',
    originalTitle: '오펜하이머',
    overview: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during the Manhattan Project.',
    posterPath: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=600&auto=format&fit=crop&q=80',
    mediaType: 'movie',
    voteAverage: 9.2,
    releaseDate: '2023',
  },
  {
    id: 'mov-3',
    title: 'Alien: Romulus',
    originalTitle: '에이리언: 로물루스',
    overview: 'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.',
    posterPath: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    mediaType: 'movie',
    voteAverage: 8.4,
    releaseDate: '2024',
  },
  {
    id: 'mov-4',
    title: '12.12: The Day',
    originalTitle: '서울의 봄',
    overview: 'On December 12, 1979 in Seoul, military officers stage a coup d\'état leading to a tense stand-off that changes Korea\'s modern history.',
    posterPath: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&auto=format&fit=crop&q=80',
    mediaType: 'movie',
    voteAverage: 9.3,
    releaseDate: '2023',
  },
];

export const MOCK_TOP_ANIMATION: MediaItem[] = [
  {
    id: 'anim-1',
    title: 'Demon Slayer: Hashira Training Arc',
    originalTitle: '귀멸의 칼날: 합동 강화 훈련편',
    overview: 'Tanjiro visits the Stone Hashira, Himejima, who intends to prepare him for the upcoming battles in the Hashira Training program.',
    posterPath: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
    mediaType: 'anime',
    voteAverage: 9.1,
    releaseDate: '2024',
  },
  {
    id: 'anim-2',
    title: 'Frieren: Beyond Journey\'s End',
    originalTitle: '장송의 프리렌',
    overview: 'An elf mage and her companions defeat the Demon King. As her human companions pass away from old age, Frieren embarks on a journey to understand human emotions.',
    posterPath: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    mediaType: 'anime',
    voteAverage: 9.5,
    releaseDate: '2023',
  },
  {
    id: 'anim-3',
    title: 'Jujutsu Kaisen Season 2',
    originalTitle: '주술회전 2기',
    overview: 'Past secrets of Gojo Satoru and Geto Suguru resurface during their high school days before the catastrophic Shibuya Incident erupts.',
    posterPath: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    mediaType: 'anime',
    voteAverage: 9.3,
    releaseDate: '2023',
  },
];

export function createMockEpisodes(mediaId: string, count: number = 8): Episode[] {
  return Array.from({ length: count }, (_, i) => ({
    id: `${mediaId}-ep-${i + 1}`,
    mediaId,
    seasonNumber: 1,
    episodeNumber: i + 1,
    title: `Episode ${i + 1}`,
    overview: `Key plot advancements and high suspense sequences unfold in episode ${i + 1}.`,
    stillPath: `https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&auto=format&fit=crop&q=80`,
    airDate: `2024-0${Math.min(9, Math.floor(i / 2) + 1)}-${(i * 3 + 1).toString().padStart(2, '0')}`,
  }));
}
